name: publish to npm
on:
  push:
    tags:
    - "v*.*.*"

jobs:
  publish:
    runs-on: macos-13
    environment: publish
    steps:
    - name: checkout code
      uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0

    - name: setup pnpm
      uses: pnpm/action-setup@c3b53f6a16e57305370b4ae5a540c2077a1d50dd # v2.2.4

    - name: setup node
      run: pnpm node -v

    - name: print store path
      id: store-path
      run: echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

    - name: cache pnpm store
      uses: actions/cache@69d9d449aced6a2ede0bc19182fadc3a0a42d2b0 # v3.2.6
      with:
        path: ${{ steps.store-path.outputs.STORE_PATH }}
        key: pnpm-store-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: pnpm-store-${{ runner.os }}

    - name: install node deps
      working-directory: js
      run: pnpm i

    - name: "publish to npm"
      run: |
        cp .github/.npmrc js/.npmrc
        VERSION=${GITHUB_REF#refs/*/v} node .github/prepare.cjs
        cd js
        npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
